### ISSUE TITLE
Build Passing?

### ISSUE THREAD

**Issue by nelsonic** [thomasdavis/w3cjs#15]
Travis build does **not complete** https://travis-ci.org/thomasdavis/w3cjs/builds/38617513  

![w3cjs-build-fails-but-badge-says-pass](https://cloud.githubusercontent.com/assets/194400/5650299/0382b7e2-9695-11e4-98d2-e016c262464b.png)

and yet the badge is ***passing***...?  [![Build Status](https://secure.travis-ci.org/thomasdavis/w3cjs.png?branch=master)](http://travis-ci.org/thomasdavis/w3cjs)

@joshk is this *desired* behaviour for Travis-CI?

**Comment by joshk** [comment]
That build was for a PR, PR builds do not affect the build badges.

**Comment by nelsonic** [comment]
Thanks for pointing that out Josh. Closed.
