### ISSUE TITLE
"This interface to HTML5 document checking is deprecated"

### ISSUE THREAD

**Issue by bfred-it** [thomasdavis/w3cjs#17]
Apparently [the current validator is deprecated](http://stackoverflow.com/questions/30716156/this-interface-to-html5-document-checking-is-deprecated-whats-the-meaning), how easy is it to move to [/nu/](https://validator.w3.org/nu/)?

For now it'd be great to just hide the warning

**Comment by callumacrae** [comment]
Unless @thomasdavis (or you) plans on doing it, I'll write and send a PR moving w3cjs to /nu/ this weekend

https://github.com/swillner/gulp-w3cnu

**Comment by thomasdavis** [comment]
Haven't had time to investigate fully, is the /nu/ endpoint relatively similar?

**Comment by thomasdavis** [comment]
Is there enough w3c tools to warrant a new organization for managing these client libs too?

**Comment by callumacrae** [comment]
Doesn't look that different. Here's how html-validator did it: https://github.com/zrrrzzt/html-validator/commit/9d899ff50ed377546d8c82e1fc1a7b11392d7e63

I'm not familiar with any of their other tools!

**Comment by thomasdavis** [comment]
So I've merged @swillner PR and updated the modules version to 0.3.0 and pushed to NPM.

Great work!
