### ISSUE TITLE
0.3.1 is not backwards compatible with 0.3.0 and so causes failures with loose version matching

### ISSUE THREAD

**Issue by amclin** [thomasdavis/w3cjs#33]
Recent update to v0.3.1 is breaking things. We're seeing errors in our logs where the response from W3C is now null:
    Uncaught TypeError: Cannot read property 'messages' of null
    at callback (test/lint/html/htmllint.js:66:16)
    at node_modules/w3cjs/lib/w3cjs.js:57:4
    at Request.callback (node_modules/superagent/lib/node/index.js:668:14)
    at node_modules/superagent/lib/node/index.js:883:18
    at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/parsers/json.js:16:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

0.3.1 is clearly not "compatible with" 0.3.0 and fails when using "w3cjs": "^0.3.0"

0.3.1 should be fixed to that it is compatible, or else rescinded and republished as 0.4.0 so that it doesn't flag as compatible with 0.3.0

**Comment by nick11703** [comment]
Looks like there was an error argument added to the callback at the front of the list. If the user is expecting the response instead of the error this will cause unintended results.
https://github.com/thomasdavis/w3cjs/pull/32/files

**Comment by thomasdavis** [comment]
I've started locking my dependencies to stop things like this happening in my project. Damn library authors! =D

We will probably keep this change so it might be better for you to use the old version or support the new err parameter.

I suppose I messed up the semver in this case though. Will look into it.

**Comment by callumacrae** [comment]
It would probably be better to revert this change, release as 0.3.2, then make the change again and release as 0.4.0.

In _theory_ you haven't messed up semver because it's <1.0.0, so you can make breaking changes on any release, but it would be better to do it on a minor release (or just release 1.0.0).

**Comment by thomasdavis** [comment]
I will do this now, thanks!

**Comment by thomasdavis** [comment]
Sorry everybody, everything should be in working order now.

0.3.2 doesn't have breaking changes.
0.4.0 is published and documentation reflects the new API changes.
