### ISSUE TITLE
Allow headings in legends

### ISSUE THREAD

**Issue by NickColley** [thomasdavis/w3cjs#38]
Hello :)

In the new version of the HTML spec, headings can be put inside legends.

We do this to avoid duplicating headings and legends when asking users for questions: https://design-system.service.gov.uk/patterns/question-pages/

See https://www.w3.org/TR/html52/sec-forms.html#the-legend-element for the updated spec.

And https://github.com/alphagov/govuk-frontend/issues/1080 for an issue raised based on using w3cjs.

Let me know if you need any more information. 😄

**Comment by jhermsmeier** [comment]
This module just consults [validator.w3.org/nu/](http://validator.w3.org/nu/), and hence couldn't fix that here. There is an issue about this on the validator already though: https://github.com/validator/validator/issues/732

**Comment by NickColley** [comment]
Ah sweet, thanks for your patience! Will close this out.

**Comment by sideshowbarker** [comment]
> In the new version of the HTML spec, headings can be put inside legends.

https://www.w3.org/TR/html52/ isn’t actually the new version of the HTML spec. In fact at this point it’s obsolete and shouldn’t be used for anything. The only HTML spec that should be used is the canonical HTML spec at https://html.spec.whatwg.org/ — which has always disallowed headings in `legend`.
